vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.netrw_browse_split = 0
vim.g.netrw_banner = 0

vim.opt.backup = false
vim.opt.clipboard = 'unnamedplus'
vim.opt.colorcolumn = '120'
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.list = true
vim.opt.listchars = {
  space = '·',
  tab = '>-',
  eol = '¬',
}
vim.opt.incsearch = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 8
vim.opt.shiftwidth = 4
vim.opt.signcolumn = 'yes'
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.timeout = true
vim.opt.timeoutlen = 250
vim.opt.undofile = true
vim.opt.updatetime = 250
vim.opt.wrap = false
